const fs = require('node:fs');
const path = require('node:path');
const pages = {
  'terms.html': ['Terms and Conditions', `
<p class="legal-note">Version 2026-10-03. Mat Rank is preparing an adults-only launch. Public registration remains closed until email delivery and operating arrangements are ready.</p>
<h2>Who operates Mat Rank</h2><p>Mat Rank is operated by Badr Choudhary. Contact <a href="mailto:badrc124@gmail.com">badrc124@gmail.com</a> for help, complaints, privacy requests or safety concerns.</p>
<h2>What Mat Rank does</h2><p>Mat Rank lets fighters log remembered rounds after training. Partners can confirm, propose corrected counts, or close a recap as unverified. Pending recaps expire after 14 days without a rating change. Only mutually agreed wins and losses count towards Elo; rounds with no winner do not. Each partner pair has one recap per training date. It is not an official competition authority, medical service, coaching service or a way to decide whether two people can safely compete. Follow your club's safeguarding rules, qualified coaches and competition rules.</p>
<h2>Adults-only service</h2><p>You must be aged 18 or over to create or use an account. Do not register on behalf of a child or let a child use your account. If we learn that an account belongs to a child, we may restrict it while we assess deletion and safeguarding needs. Contact us if you believe a child is using the service. Children's accounts are not offered in this release.</p>
<h2>Your account</h2><p>Choose a nickname and a unique password. Do not use someone else's identity, share credentials or put private details such as your address or school into a nickname or comment. You are responsible for activity you authorise through your account. Tell us if you think someone has gained access. Use an email address you control and verify it before completing signup. Use Forgot password on the sign-in page to request a reset link. Resetting your password signs out all devices. Older accounts must first add and verify a recovery email. Support will not ask you to send your password.</p>
<h2>Fair use and safety</h2><p>Submit truthful results and use the service respectfully. A confirmed recap cannot be edited in the app; contact the operator if a correction is needed. Do not post bullying, threats, hate, sexual content, exploitation, illegal material, private information about others, spam or impersonation. Do not use the app to arrange unsafe contact with children. Do not attempt to compromise the service or other accounts.</p>
<h2>Reporting and moderation</h2><p>Report concerns to <a href="mailto:badrc124@gmail.com">badrc124@gmail.com</a>, including the nickname, match number and a short description. Do not send illegal images or unnecessary personal information. For immediate danger contact emergency services. We may remove harmful content or restrict accounts that break these rules. We will explain our decision where appropriate and consider an appeal sent to the contact address above. Public launch remains subject to documented safety and moderation procedures. Decisions can be challenged using the same contact address. Nothing in these terms removes any legal right to bring a claim for breach of contract.</p>
<h2>Your content and information</h2><p>You retain ownership of your original content. You give Mat Rank permission to store and display it only as needed to provide the service. Do not submit content you have no right to share. In the current preview, nicknames, rankings, profile details, results and comments can be seen by other signed-in users; they must not contain children's identifying details. The service is for adults only. Do not publish information identifying children.</p>
<h2>Leaving and deleting an account</h2><p>Use Account &amp; privacy to export information or delete your account. Deletion removes your profile, authored comments, likes, sessions and pending requests from the live database. Completed results remain under “Deleted account” for opponents; this is not guaranteed anonymisation because others may recognise matches. Contact us about removal of identifiable retained records or backup copies.</p>
<h2>Availability and your rights</h2><p>We aim to keep records accurate and the service available, but interruptions and mistakes can occur. Rankings are estimates. Nothing here excludes liability for death or personal injury caused by negligence, fraud, or any liability or consumer right that law does not permit us to exclude. There is currently no paid subscription or checkout.</p>
<h2>Changes and governing law</h2><p>Material changes will be explained before they apply where required; continued use alone is not consent to new optional data processing. These preview terms use the law of England and Wales, without removing mandatory protections or rights to use courts available where you live in the UK.</p>`],
  'privacy.html': ['Privacy Notice', `
<p class="legal-note">Preview notice · version 2026-10-03. Controller: Badr Choudhary, <a href="mailto:badrc124@gmail.com">badrc124@gmail.com</a>. This release is for adults aged 18 or over. Public registration is closed while email delivery and launch arrangements are completed.</p>
<h2>Who can use this release</h2><p>Mat Rank is for adults aged 18 or over. Do not create an account for a child or share your account with one. We record your age confirmation without collecting your full date of birth. Please contact us if you believe we hold a child's information so we can assess and address it.</p>
<h2>What we collect</h2><p>Private verified email address, adult-age confirmation, account nickname, a salted password hash (not a readable password), profile details you enter (belt, weight, division and gym), after-training recap dates, proposed round counts, review status and confirmed results, Elo scores, training logs and streaks, likes, comments, account creation time and records of the terms accepted and privacy notice shown. We temporarily store pending signup information and hashed email-verification and password-reset tokens. We also store hashed session tokens and temporary hashed identifiers for request limiting. Hosting providers process connection data such as IP addresses and operational logs. Do not submit health information or children's identifying details.</p>
<h2>Why we use it</h2><p>We use account and match information to provide the requested ranking service and handle your requests. The lawful basis for adult account services, verification and recovery emails is performance of a contract. Security, abuse prevention and service integrity rely on legitimate interests, subject to a documented balancing assessment. Legally required records rely on legal obligation where applicable. Children are not permitted to register in this release. We must still assess the likelihood of children accessing the service and maintain proportionate safeguards. Accepting the terms is not blanket consent for data processing or marketing.</p>
<h2>Who can see it</h2><p>The current preview is gated by sign-in, but signed-in users can see nicknames, profile fields, results, rankings, comments and likes. Email addresses are private and are not included in the roster or match feed. Passwords and session secrets are not exposed through profiles or exports. Railway is being configured for hosting and Resend for account emails. Hosting region, persistent storage and live email delivery have not yet been verified. The operator must confirm processor contracts, any international transfers and applicable safeguards before opening registration. We do not sell personal data or add advertising or analytics trackers.</p>
<h2>How long we keep it</h2><p>Profile data remains while the account is active until deletion is requested. Session validity is seven days; expired session rows are removed by hourly maintenance. Rate-limit records expire after up to one hour and are cleaned by hourly maintenance. Terms acceptance records are held with the account. Deleting an account removes profile details and authored comments from the live database, but keeps completed match results under “Deleted account” for opponents; these may still be identifiable by context. Unverified signup and email-link requests expire after 24 hours; reset links expire after 30 minutes. Expired token records are removed hourly. Password changes and resets invalidate outstanding reset links. A verified production backup and deletion schedule must be established before launch. The operator still needs to approve and implement inactivity, retained-match, complaint and operational-log retention periods before launch.</p>
<h2>Your choices and rights</h2><p>Correct profile details in Profile. Use Account &amp; privacy to download your information, change your password, sign out devices or delete your account. You may also request access, correction, erasure, restriction and portability, or object to processing where applicable, by emailing us. We may need proportionate identity checks, but will never ask you to email your password. Requests are normally due a response within one month, with lawful extensions where applicable. You can complain to the <a href="https://ico.org.uk/make-a-complaint/">Information Commissioner's Office</a>.</p>
<h2>Rankings and automation</h2><p>Elo rankings are calculated automatically from mutually confirmed results and belt settings. Within each recap, decisive rounds use the same pre-confirmation ratings and their changes are summed because round order is unknown. Different recaps are applied in confirmation order. They are informal sporting estimates and do not determine access to employment, credit or legal rights. Contact us to challenge incorrect records. The privacy and wellbeing impact of ranking children must be assessed before launch.</p>
<h2>Cookies and security</h2><p>We use a strictly necessary sign-in cookie, described in the <a href="/cookies.html">Cookie Notice</a>. Passwords are salted and hashed with scrypt. Sessions expire and can be revoked. Production cookies require HTTPS and are not readable by JavaScript. Email verification and password recovery are implemented; availability depends on a verified sender domain. We do not currently offer multi-factor authentication. These controls reduce risk but do not promise absolute security.</p>`],
  'cookies.html': ['Cookie Notice', `
<p>Version 2026-10-03 · Badr Choudhary · <a href="mailto:badrc124@gmail.com">badrc124@gmail.com</a></p>
<h2>Only essential cookies</h2><p>Mat Rank uses a first-party cookie called <strong>matrank_session</strong> after you sign in or register. It keeps you signed in when you refresh or return to the app. It expires after seven days. Signing out invalidates it and removes it from your browser. Changing your password invalidates other sessions; “Sign out every device” invalidates all sessions.</p>
<p>The cookie is HttpOnly, SameSite=Lax and Secure in production. It contains a random session value, not your password. The server stores a hash of that value. The cookie is needed to provide the account service you request, so it does not depend on optional cookie consent.</p>
<h2>No advertising or analytics</h2><p>This version sets no optional advertising or analytics cookies and loads no third-party fonts or tracking scripts. There is no “accept all” requirement. If optional technologies are added later, they must stay off until an appropriate consent mechanism is implemented, with an equally accessible rejection and withdrawal choice.</p>
<h2>Remembering this notice</h2><p>When you select “Got it”, we store the notice version in local storage under <strong>matrank_cookie_notice</strong> to remember your requested dismissal. It remains until you clear website data or a new notice version is published. This is not marketing consent. Use “Cookie information” in the app to show the notice again.</p><h2>Your browser controls</h2><p>You can block or delete cookies in your browser, but account features will not work without the sign-in cookie. An obsolete local-storage sign-in token from earlier versions is removed when the app loads. No new authentication token is saved in local storage.</p>`]
};
for (const [file, [title, content]] of Object.entries(pages)) {
  fs.writeFileSync(path.join(__dirname, '..', 'public', file), `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — Mat Rank</title><link rel="stylesheet" href="/css/styles.css"><link rel="stylesheet" href="/css/legal.css"></head><body><main class="legal-page"><a href="/">← Back to Mat Rank</a><h1>${title}</h1>${content}<hr><nav aria-label="Legal"><a href="/terms.html">Terms</a> · <a href="/privacy.html">Privacy</a> · <a href="/cookies.html">Cookies</a></nav></main></body></html>`);
}
